apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: rpi-demo
  namespace: rpi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rpi-demo-app
  maxReplicas: 20
  minReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
